### ISSUE TITLE
PDF support

### ISSUE THREAD

**Issue by T7Droid** [iamarbaazkhan/Simple-Page-Curl-Effect-Android#2]
Hi, thank you for this library!

It is really simple and easy to use, and has a beautiful animation. I just would like to ask you: is it possible for you to make the pageCurlView receive a list of bitmap and not only a list of Integer (drawable)?

For example, override this method: 

`List<Integers> images = new ArrayList<>();`

`pageCurlView.setCurlView(images);`

to

`List<Bitmap> bitmaps = new ArrayList<>();`

`pageCurlView.setCurlView(bitmaps);`

Because now a can use only images from assets folder, but I would like to load a bitmap extracted from a pdf too.

**Comment by T7Droid** [comment]
I have already implemented it, thank you!

**Comment by iamarbaazkhan** [comment]
Hi @T7Droid , 
        Thanks for using this library I appreciate your feedback  and  you need any other help please let me know :)
