### ISSUE TITLE
how to pass image url 

### ISSUE THREAD

**Issue by hinditutorpoint** [iamarbaazkhan/Simple-Page-Curl-Effect-Android#3]
hi
how to pass sdcard images as list where 
List<string> list = new Arrarylist<>();
list.add("sdcard/");
pagecurl.setCurlView(list)

**Comment by iamarbaazkhan** [comment]
Hi @hinditutorpoint, 
       I am not getting your issue can you please elaborate more and as you can see in the project you can use the local images right now in the apk.
