### ISSUE TITLE
Как загибать изображение слева направо для слов на Арабском языке

### ISSUE THREAD

**Issue by Neo3437** [iamarbaazkhan/Simple-Page-Curl-Effect-Android#4]
Добрый вечер! Спасибо вам за ваш труд в создании данной библиотеки! Я новичок в Android программировании, сейчас делаю приложение КОРАН, и мне нужна ваша помощь ))
Скажите пожалуйста как можно изменить библиотеку, что бы можно было начинать перелистывать страницы слева направо  для слов на Арабском языке?

**Comment by iamarbaazkhan** [comment]
Привет, спасибо за использование этой библиотеки в вашем приложении для Android, и вы можете использовать эту библиотеку с языком, поскольку она работает только с макетом страницы, а не с конкретным языком.
